### ISSUE TITLE
[Bug]: My gta v game crashes when I inject it

### ISSUE THREAD

**Issue by Maxi23-1** [lonelybud/lonelyMenu#49]
### Describe the bug

When I try to inject the .dll, my gta v crashes

### Steps To Reproduce

Inject the .dll into Gta V

### Expected Behavior

to work 

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

I used xenos injector to inject the menu dll

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
can you attach `cout.log` file please. also please mention when do you inject the game - in menu, single player or online? what injector you use and any setting you did in that injector

**Comment by lonelybud** [comment]
you can find log file in `X:\Users\XXX\AppData\Roaming\YimMenu` folder

**Comment by lonelybud** [comment]
if you have used yim menu before than please backup your folder `X:\Users\XXX\AppData\Roaming\YimMenu` and then delete it. Do a clean inject of this menu bcz this menu has breaking changes related to settings it create

**Comment by lonelybud** [comment]
no reply.
